from utils import *


questions = {
    'CV1': "Unscramble the group of letters: <QUESTION>, to form a common English word. Use all the letters in each group. Respond with only a word.",
    'CV2': "Find hidden four-letter English words in a line of letters: <QUESTION>. Ruless: (1) Look for words made of four letters. (2) You can only use each letter once—no overlapping words. (3) Read the line from left to right. (4) There can be one to five hidden words in a line. Respond with only the words, one word per line.",
    'CV3': "You will see words with missing letters. The missing letter is shown as a blank (_). Your task is to fill in each blank with one letter to complete the word in <QUESTION>. Respond with only a word.",
    'FA1': "Think of as many words as possible that have the same or similar meaning as <QUESTION>. Respond with only the words, one word per line.",
    'FA2': "Your job is to write as many words as possible that mean the opposite of <QUESTION>. Respond with only the words, one word per line.",
    'FA3': "Think of words or phrases that compare one thing to another using figures of speech. <QUESTION>? Respond with only the words, one word per line.",
    'FE1': "Write a sentence using words that begin with <QUESTION>. You must use the letters and asterisks (*) in the exact order shown. Each letter must start a word, and each asterisk can be any word of your choice. Respond with only the sentence.",
    'FE2': "Write as many different sentences as you can using all four of the words in: <QUESTION>. Rules: (1) Use each word exactly as it is (no changes in form). (2) Each sentence must be different in more than just one or two words. (3) Sentences can be any length. Respond with only the sentences, one sentence per line.",
    'FE3': "",
    'FI1': "",
    'FI2': "",
    'FI3': "",
    'FW1': "",
    'FW2': "",
    'FW3': "",
    'I1': "",
    'I2': "",
    'MA2': "",
    'MA3': "",
    'RG1': "",
    'RG2': "",
    'RG3': "",
    'RL1': "",
    'RL3': "",
    'RL4': "",
    'V1': "",
    'V2': "",
    'V3': "",
    'V4': "",
    'V5': "",
    'XU1': "",
    'XU2': "",
    'XU3': "",
    'XU4': "",
}

demonstrations = {
    'CV1': "",
    'CV2': "",
    'CV3': "",
    'FA1': "",
    'FA2': "",
    'FA3': "",
    'FE1': "",
    'FE2': "",
    'FE3': "",
    'FI1': "",
    'FI2': "",
    'FI3': "",
    'FW1': "",
    'FW2': "",
    'FW3': "",
    'I1': "",
    'I2': "",
    'MA2': "",
    'MA3': "",
    'RG1': "",
    'RG2': "",
    'RG3': "",
    'RL1': "",
    'RL3': "",
    'RL4': "",
    'V1': "",
    'V2': "",
    'V3': "",
    'V4': "",
    'V5': "",
    'XU1': "",
    'XU2': "",
    'XU3': "",
    'XU4': "",
}

dataset = TextFRCT('TextFRCT.csv')

for row in dataset.build_prompt():
    print(row)